services:
  # Monolithic App: FastAPI Backend + React Frontend
  - type: web
    name: coraldarwin-cloud
    env: docker
    dockerfilePath: ./backend.Dockerfile
    plan: free # Use the free tier to avoid credit card requirements
    region: ohio
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: DEPLOYMENT_MODE
        value: cloud
      # Add API keys here securely in the Render dashboard later
      - key: NOAA_ERDDAP_BASE_URL
        value: https://coastwatch.pfeg.noaa.gov/erddap
